// playwright.config.js — Generated by agent-pipeline
// Runs QA forest tests (tests/qa/) and Design visual assertion tests (tests/design/).
// Install: npm install -D @playwright/test && npx playwright install chromium

import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './tests',
  testMatch: ['qa/**/*.spec.js', 'design/**/*.spec.js'],
  fullyParallel: false,
  forbidOnly: true,
  retries: 1,
  workers: 1,
  reporter: [['list'], ['json', { outputFile: '.qa/playwright-results.json' }]],
  use: {
    baseURL: 'http://localhost:3000',
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
  },
  projects: [
    { name: 'desktop', use: { ...devices['Desktop Chrome'] } },
  ],
  webServer: {
    command: 'npm run dev',
    url: 'http://localhost:3000',
    reuseExistingServer: true,
    timeout: 30000,
  },
});
